version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nautilus_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keti123
      POSTGRES_DB: nautilus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_table.sql:/docker-entrypoint-initdb.d/init_table.sql

volumes:
  postgres_data:
