---
- name: Load Image into containerd to Master
  hosts: "{{ target_host }}"
  become: yes  # Run tasks as root
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    local_tar_path: "{{ playbook_dir }}/../../../workspace/images/nautilus-pv-updated.tar"
    containerd_image_name: "nautilus-pv-updated:latest"

  handlers:
    - name: Reload sysctl
      command: sysctl --system

  tasks:
    - name: Convert local_tar_path to absolute path
      set_fact:
        abs_tar_path: "{{ local_tar_path | realpath }}"

    - name: Show local_tar_path
      debug:
        msg: "{{ abs_tar_path }}"

    # -------------------------------
    # Load Image into containerd
    # ctr -n k8s.io images import /home/cotlab/nautilus-env/Nautilus/nautilus/nautilus/workspace/images/nautilus-pv-updated.tar
    # -------------------------------
    - name: Check if image exists in containerd
      shell: "ctr -n k8s.io images list | grep '{{ containerd_image_name }}' || true"
      register: image_check
      changed_when: false

    - name: Remove existing image if found
      command: "ctr -n k8s.io images remove {{ containerd_image_name }}"
      when: image_check.stdout != ""

    - name: Load the image into containerd
      command: ctr -n k8s.io images import {{ abs_tar_path }}
      register: import_result

    - name: master > Show containerd import command
      debug:
        msg: "ctr -n k8s.io images import {{ abs_tar_path }}"

    - name: Show containerd import result
      debug:
        msg: "{{ import_result.stdout }}"
