---
- name: Install and Configure Kubernetes Cluster with PostgreSQL
  hosts: "{{ target_host }}"
  become: yes
  vars:
    kube_version: "1.32.0"
    cni_plugin: "calico"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install required dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
      state: present

  - name: Install Docker Compose
    apt:
      name: docker-compose
      state: present

  - name: Copy docker-compose.yml file
    copy:
      src: ../../../../init-scripts/docker-compose.yml
      dest: ../../../../init-scripts/docker-compose.yml

  - name: Copy init SQL scripts
    copy:
      src: ../../../../init-scripts/init_table.sql
      dest: ../../../../init-scripts/init_table.sql

  - name: Start PostgreSQL container
    command: docker-compose -f ./docker-compose.yml up -d
    args:
      chdir: ../../../../init-scripts/

  - name: Ensure tables are created in PostgreSQL
    command: docker exec -i nautilus_postgres psql -U postgres -d nautilus_db -f /docker-entrypoint-initdb.d/init_table.sql


  - name: Deploy MinIO using Docker
    command: docker run -d --name minio --restart always -p 9000:9000 -p 9001:9001 -e MINIO_ROOT_USER=admin -e MINIO_ROOT_PASSWORD=admin123 minio/minio server /data --console-address ":9001"

  - name: Install MinIO client (mc)
    get_url:
      url: https://dl.min.io/client/mc/release/linux-amd64/mc
      dest: /usr/local/bin/mc
      mode: '0755'

  - name: Configure MinIO client
    command: mc alias set myminio http://127.0.0.1:9000 admin admin123

  - name: Add Docker GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Add Docker repository to apt sources
    shell: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    args:
      creates: /etc/apt/sources.list.d/docker.list

  - name: Add Kubernetes GPG key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
      dest: /tmp/Release.key

  - name: Convert Kubernetes GPG key to keyring format
    command: gpg --dearmor --batch --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key

  - name: Add Kubernetes apt repository
    copy:
      dest: /etc/apt/sources.list.d/kubernetes.list
      content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'

  - name: Update apt cache after adding repositories
    apt:
      update_cache: yes

  - name: Install Docker, containerd
    apt:
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
      state: present

  - name: Configure containerd (SystemdCgroup)
    block:
      - name: Generate default containerd configuration
        command: containerd config default
        register: containerd_config

      - name: Write the containerd configuration to file
        copy:
          content: "{{ containerd_config.stdout }}"
          dest: /etc/containerd/config.toml

      - name: Enable SystemdCgroup in containerd configuration
        replace:
          path: /etc/containerd/config.toml
          regexp: '^\s*SystemdCgroup = false$'
          replace: 'SystemdCgroup = true'

      - name: Restart containerd service
        systemd:
          name: containerd
          state: restarted
          enabled: yes

  - name: Start Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install kubeadm, kubelet, and kubectl
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present
      update_cache: yes

  - name: Hold Kubernetes packages at current version
    shell: apt-mark hold kubelet kubeadm kubectl

  - name: Enable and start kubelet service
    systemd:
      name: kubelet
      enabled: yes
      state: started

  - name: Disable swap
    command: swapoff -a
    args:
      warn: false

  - name: Ensure swap is disabled in fstab
    replace:
      path: /etc/fstab
      regexp: '^.*swap.*$'
      replace: ''

  - name: Configure sysctl settings for Kubernetes networking
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
    notify: Reload sysctl

  - name: Apply sysctl settings
    command: sysctl --system

  - name: Pre-pull Kubernetes images
    command: kubeadm config images pull

  - name: Initialize Kubernetes cluster (only on master node)
    command: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all

  - name: Configure kubectl for the root user
    shell: |
      mkdir -p $HOME/.kube
      cp /etc/kubernetes/admin.conf $HOME/.kube/config
      chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Deploy network plugin (Calico)
    shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

  handlers:
    - name: Reload sysctl
      command: sysctl --system
