apiVersion: v1
kind: Pod
metadata:
  name: mylocalhost
  namespace: {{ .Values.namespace }}
  labels:
    app: mylocalhost
spec:
  nodeSelector:
    kubernetes.io/hostname: master-node
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "1Gi"
  containers:
  - name: server
    image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]
    args:
      - >
        /workspace/nautilus/nautilus/workspace/provision/{{ .Values.projectId }}/prod_00/mylocalhost/startup/sub_start.sh
    ports:
      - containerPort: 8002
      - containerPort: 8003
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    resources:
      requests:
        cpu: "4"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
  restartPolicy: Never
