apiVersion: v1
kind: Service
metadata:
  name: mylocalhost
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mylocalhost
  ports:
    - name: grpc
      port: 8002
      targetPort: 8002
    - name: control
      port: 8003
      targetPort: 8003
  type: ClusterIP
