apiVersion: v1
kind: Pod
metadata:
  name: mylocalhost
  namespace: {{ .Values.namespace }}
  labels:
    app: mylocalhost
spec:
  nodeSelector:
    kubernetes.io/hostname: master-node
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - name: server
    image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]
    args:
      - >
        pip install --upgrade nvflare==2.5.2 torch tensorboard torchvision &&
        /workspace/nautilus/nautilus/workspace/provision/{{ .Values.projectId }}/prod_00/mylocalhost/startup/sub_start.sh
    ports:
      - containerPort: 8002
      - containerPort: 8003
  restartPolicy: Never